import React, { useState, useMemo, useEffect } from 'react';
import { Registration } from './types';
import { Calendar, Trash2, Save, X, Settings2, Play, Users, GitBranch, ChevronDown, ChevronRight, BarChart2 } from 'lucide-react';
import { db, doc, writeBatch, query, collection, where, getDocs, deleteDoc, onSnapshot, updateDoc, orderBy } from './supabase_mock';
import { v4 as uuidv4 } from 'uuid';

export const ScheduleRandomizer = ({ teams }: { teams: Registration[] }) => {
  const [startDate, setStartDate] = useState(new Date().toISOString().split('T')[0]);
  const [skipSundays, setSkipSundays] = useState(true);
  const [previewData, setPreviewData] = useState<any>(null);
  const [isSaving, setIsSaving] = useState(false);
  const [saveProgress, setSaveProgress] = useState('');
  const [saveComplete, setSaveComplete] = useState(false);

  // Fixtures list states
  const [scheduledMatches, setScheduledMatches] = useState<any[]>([]);
  const [openDays, setOpenDays] = useState<Record<number, boolean>>({});
  const [showBalanceModal, setShowBalanceModal] = useState(false);

  useEffect(() => {
    // Listen to matches where we have matchday set (meaning generated by randomizer)
    const q = query(collection(db, 'matches'));
    const unsub = onSnapshot(q, (snap) => {
      const generated = snap.docs
        .map(d => {
          const m = d.data();
          const homeTeam = teams.find(t => t.id === m.homeTeamId);
          const awayTeam = teams.find(t => t.id === m.awayTeamId);
          return {
            ...m,
            id: d.id,
            homeTeamName: homeTeam?.fcName || m.homeTeamName || 'Unknown Team',
            awayTeamName: awayTeam?.fcName || m.awayTeamName || 'Unknown Team',
            scheduledDate: m.date || m.scheduledDate // sync both fields
          };
        })
        .filter(m => m.matchday !== undefined)
        .sort((a, b) => {
          if (a.matchday !== b.matchday) return (a.matchday || 0) - (b.matchday || 0);
          return (a.matchNumber || 0) - (b.matchNumber || 0);
        });
      setScheduledMatches(generated);
    });
    return () => unsub();
  }, [teams]);

  const toggleDay = (day: number) => {
    setOpenDays(prev => ({ ...prev, [day]: !prev[day] }));
  };

  const updateMatchDate = async (id: string, newDate: string) => {
    try {
      await updateDoc(doc(db, 'matches', id), { date: newDate, scheduledDate: newDate });
    } catch(err) {
      console.error(err);
    }
  };

  const matchesByDay = useMemo(() => {
    const acc: Record<number, any[]> = {};
    scheduledMatches.forEach(m => {
      acc[m.matchday] = acc[m.matchday] || [];
      acc[m.matchday].push(m);
    });
    return acc;
  }, [scheduledMatches]);

  const stats = useMemo(() => {
    if (scheduledMatches.length === 0) return null;
    let daysCnt = Object.keys(matchesByDay).length;
    let totalM = scheduledMatches.filter(m => !m.isBye).length;
    let sDate = scheduledMatches[0].scheduledDate;
    let eDate = scheduledMatches[scheduledMatches.length - 1].scheduledDate;
    let amt = matchesByDay[1]?.filter((m: any) => !m.isBye).length || 0;
    
    const hCount: Record<string, number> = {};
    const aCount: Record<string, number> = {};
    teams.forEach(t => { hCount[t.fcName] = 0; aCount[t.fcName] = 0; });
    
    scheduledMatches.forEach(m => {
      if (!m.isBye) {
        if (hCount[m.homeTeamName] !== undefined) hCount[m.homeTeamName]++;
        if (aCount[m.awayTeamName] !== undefined) aCount[m.awayTeamName]++;
      }
    });

    return { daysCnt, totalM, sDate, eDate, amt, hCount, aCount };
  }, [scheduledMatches, matchesByDay, teams]);

  const generatePairs = (teamsList: Registration[]) => {
    const isOdd = teamsList.length % 2 !== 0;
    const paddedTeams = isOdd ? [...teamsList, { fcName: 'BYE', id: 'bye' } as Registration] : [...teamsList];
    const n = paddedTeams.length;
    const numRounds = n - 1;
    const rounds = [];
    
    // Copy array to mutate
    let currentTeams = [...paddedTeams];
    
    for (let round = 1; round <= numRounds; round++) {
      const roundPairs = [];
      for (let i = 0; i < n / 2; i++) {
        roundPairs.push([currentTeams[i], currentTeams[n - 1 - i]]);
      }
      rounds.push(roundPairs);
      // rotate clockwise keeping idx 0 stable
      const first = currentTeams[0];
      const rest = currentTeams.slice(1);
      const last = rest.pop()!;
      rest.unshift(last);
      currentTeams = [first, ...rest];
    }
    return rounds;
  };

  const nextIsoDate = (isoStr: string) => {
    const d = new Date(isoStr);
    d.setUTCHours(12);
    d.setUTCDate(d.getUTCDate() + 1);
    if (skipSundays && d.getUTCDay() === 0) {
      d.setUTCDate(d.getUTCDate() + 1);
    }
    return d.toISOString().split('T')[0];
  };

  const handleGenerate = () => {
    setSaveComplete(false);
    if (teams.length < 2) {
      alert("Need at least 2 registered teams");
      return;
    }

    const rounds = generatePairs(teams);
    const homeCount: Record<string, number> = {};
    const awayCount: Record<string, number> = {};
    const history: Record<string, string[]> = {};
    
    teams.forEach(t => { 
      homeCount[t.fcName] = 0; 
      awayCount[t.fcName] = 0; 
      history[t.fcName] = []; 
    });
    
    const allMatches = [];
    
    let currentDay = 1;
    let currDate = startDate;
    let dateIsSunday = new Date(currDate).getUTCDay() === 0;
    if (skipSundays && dateIsSunday) {
        currDate = nextIsoDate(currDate);
    }
    let matchesThisDay: Record<string, number> = {};
    
    let matchNum = 1;
    
    // Process round by round
    rounds.forEach((roundPairs, roundIdx) => {
      // Shuffle pairs within the round optionally, but we process them sequentially
      roundPairs.forEach(pair => {
         let [t1, t2] = pair;
         if (t1.id === 'bye' || t2.id === 'bye') {
           const realTeam = t1.id === 'bye' ? t2 : t1;
           allMatches.push({
             id: uuidv4(),
             homeTeamId: realTeam.id,
             awayTeamId: 'bye',
             homeTeamName: realTeam.fcName,
             awayTeamName: 'BYE',
             scheduledDate: currDate,
             matchday: currentDay,
             round: roundIdx + 1,
             status: 'bye',
             isBye: true
           });
           return;
         }
         
         let home = t1;
         let away = t2;
         
         const t1Hist = history[t1.fcName];
         const t2Hist = history[t2.fcName];
         const t1StreakHome = t1Hist.length >= 2 && t1Hist[t1Hist.length-1] === 'H' && t1Hist[t1Hist.length-2] === 'H';
         const t1StreakAway = t1Hist.length >= 2 && t1Hist[t1Hist.length-1] === 'A' && t1Hist[t1Hist.length-2] === 'A';
         const t2StreakHome = t2Hist.length >= 2 && t2Hist[t2Hist.length-1] === 'H' && t2Hist[t2Hist.length-2] === 'H';
         const t2StreakAway = t2Hist.length >= 2 && t2Hist[t2Hist.length-1] === 'A' && t2Hist[t2Hist.length-2] === 'A';

         if (t1StreakHome || t2StreakAway) {
             home = t2; away = t1;
         } else if (t1StreakAway || t2StreakHome) {
             home = t1; away = t2;
         } else if (homeCount[t1.fcName] < homeCount[t2.fcName]) {
            home = t1; away = t2;
         } else if (homeCount[t2.fcName] < homeCount[t1.fcName]) {
            home = t2; away = t1;
         } else {
            if (Math.random() > 0.5) { home = t1; away = t2; }
            else { home = t2; away = t1; }
         }
         
         // Enforce max 2 matches per day constraint:
         if ((matchesThisDay[home.fcName] || 0) >= 2 || (matchesThisDay[away.fcName] || 0) >= 2) {
            currentDay++;
            currDate = nextIsoDate(currDate);
            matchesThisDay = {};
         }
         
         matchesThisDay[home.fcName] = (matchesThisDay[home.fcName] || 0) + 1;
         matchesThisDay[away.fcName] = (matchesThisDay[away.fcName] || 0) + 1;
         homeCount[home.fcName]++;
         awayCount[away.fcName]++;
         
         history[home.fcName].push('H');
         history[away.fcName].push('A');
         
         allMatches.push({
           id: uuidv4(),
           homeTeamId: home.id,
           awayTeamId: away.id,
           homeTeamName: home.fcName,
           awayTeamName: away.fcName,
           scheduledDate: currDate,
           matchday: currentDay,
           matchNumber: matchNum++,
           round: roundIdx + 1,
           status: 'scheduled',
           homeScore: null,
           awayScore: null,
           isBye: false
         });
      });
    });

    setPreviewData({
      matches: allMatches,
      stats: {
        totalMatches: allMatches.filter((m: any) => !m.isBye).length,
        totalDays: currentDay,
        startDate: allMatches[0].scheduledDate,
        endDate: allMatches[allMatches.length - 1].scheduledDate,
        homeCount,
        awayCount
      }
    });
  };

  const handleSave = async () => {
    if (!previewData) return;
    setIsSaving(true);
    setSaveProgress('Checking existing matches...');
    try {
      // 1. Delete all matches docs where status=scheduled, score null
      const q = query(
         collection(db, 'matches'), 
         where('status', '==', 'scheduled')
      );
      const snap = await getDocs(q);
      const toDelete = snap.docs.filter(d => {
         const data = d.data();
         return data.homeScore === null && data.awayScore === null;
      });
      
      setSaveProgress(`Deleting ${toDelete.length} existing unplayed fixtures...`);
      // Delete individually or in batches
      const delBatch = writeBatch(db);
      toDelete.forEach(d => delBatch.delete(d.ref));
      await delBatch.commit();
      
      const { matches } = previewData;
      let total = matches.length;
      setSaveProgress(`Saving matches... 0 of ${total}`);
      
      // Batches of 50
      for (let i = 0; i < matches.length; i += 50) {
        const batchMap = writeBatch(db);
        const chunk = matches.slice(i, i + 50);
        for (const match of chunk) {
          if (match.isBye) {
            continue;
          }
          const dbMatch = {
             id: match.id,
             homeTeamId: match.homeTeamId,
             awayTeamId: match.awayTeamId,
             date: match.scheduledDate,
             scheduledDate: match.scheduledDate,
             matchday: match.matchday,
             matchNumber: match.matchNumber,
             status: 'scheduled',
             homeScore: null,
             awayScore: null,
             homeScorers: [],
             awayScorers: [],
             editLogs: []
          };
          batchMap.set(doc(db, 'matches', match.id), dbMatch);
        }
        await batchMap.commit();
        setSaveProgress(`Saving matches... ${Math.min(i + 50, total)} of ${total}`);
      }
      
      setSaveComplete(true);
      setPreviewData(null);
    } catch(err: any) {
      alert("Error saving: " + err.message);
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <div className="space-y-8 mt-6">
      <div className="bg-white/5 border border-white/10 p-4 md:p-6 rounded-sm">
        <div className="flex flex-col md:flex-row md:items-end gap-6 mb-4">
          <div className="flex-1 space-y-2">
             <label className="text-[10px] font-black uppercase text-white/40 mb-1 flex items-center gap-2">
               📅 Start Date
             </label>
             <input 
               type="date" 
               value={startDate}
               onChange={e => setStartDate(e.target.value)}
               className="w-full bg-black/20 border border-white/10 rounded-sm p-4 text-white uppercase font-black text-sm outline-none focus:border-fc-neon-green/50 transition-all"
             />
          </div>
          
          <div className="flex items-center gap-3 px-4 py-4 md:py-0 h-full min-h-[56px] border border-white/5 rounded-sm bg-black/10">
            <input
              type="checkbox"
              id="skipSundays"
              checked={skipSundays}
              onChange={e => setSkipSundays(e.target.checked)}
              className="w-5 h-5 accent-fc-neon-green"
            />
            <label htmlFor="skipSundays" className="text-xs font-black uppercase text-white/80 tracking-widest cursor-pointer mt-1">Skip Sundays</label>
          </div>
          
          <button 
            onClick={handleGenerate}
            className="px-8 py-4 bg-fc-neon-green text-black hover:bg-fc-purple-light rounded-sm font-black uppercase text-xs tracking-widest transition-all shadow-xl shadow-fc-neon-green/20 h-full min-h-[56px] flex items-center justify-center gap-2"
          >
            <Play className="w-4 h-4" /> Generate Schedule
          </button>
        </div>
      </div>

      {stats && (
        <div className="bg-white/5 border border-white/10 rounded-sm">
          <div className="flex flex-col md:flex-row items-start md:items-center justify-between p-4 bg-black/20 border-b border-white/5 gap-4">
             <div className="flex flex-wrap items-center gap-4 text-xs font-black uppercase tracking-widest text-white/80">
                <span>{stats.totalM} matches</span>
                <span className="text-white/20">•</span>
                <span>{stats.daysCnt} days</span>
                <span className="text-white/20">•</span>
                <span className="text-fc-neon-green">{new Date(stats.sDate).toLocaleDateString('en-US', {month: 'short', day: 'numeric'})} → {new Date(stats.eDate).toLocaleDateString('en-US', {month: 'short', day: 'numeric'})}</span>
                <span className="text-white/20">•</span>
                <span>~{stats.amt} matches/day</span>
             </div>
             
             <button onClick={() => setShowBalanceModal(true)} className="flex items-center gap-2 px-4 py-2 bg-white/5 hover:bg-white/10 border border-white/10 rounded-sm text-[10px] font-black uppercase tracking-widest transition-all text-white">
                <BarChart2 className="w-4 h-4 text-fc-neon-green" /> View Balance
             </button>
          </div>
          
          <div className="p-4 space-y-4 max-h-[800px] overflow-y-auto hide-scrollbar">
             {Object.keys(matchesByDay).map(d => {
               const dayNum = Number(d);
               const dayMatches = matchesByDay[dayNum];
               const dObj = new Date(dayMatches[0].scheduledDate);
               const dateStr = dObj.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' });
               const isOpen = openDays[dayNum];
               
               return (
                 <div key={dayNum} className="border border-white/5 bg-black/20 rounded-sm overflow-hidden">
                    <button onClick={() => toggleDay(dayNum)} className="w-full flex items-center justify-between p-4 bg-white/5 hover:bg-white/10 transition-colors focus:outline-none">
                       <div className="flex items-center gap-3">
                         {isOpen ? <ChevronDown className="w-4 h-4 text-fc-neon-green" /> : <ChevronRight className="w-4 h-4 text-white/40" />}
                         <span className="text-xs font-black uppercase tracking-widest text-white">📅 Day {dayNum} — {dateStr}</span>
                       </div>
                       <span className="text-[10px] font-black uppercase tracking-widest text-white/40">{dayMatches.length} matches</span>
                    </button>
                    
                    {isOpen && (
                       <div className="p-4 space-y-2 bg-black/40">
                          {dayMatches.map((m: any) => m.isBye ? (
                            <div key={m.id} className="flex items-center gap-4 py-3 pl-2 sm:pl-8 border-b border-white/5 last:border-0">
                               <span className="text-[10px] font-black uppercase text-yellow-500/70 tracking-widest">🔄 {m.homeTeamName} — BYE this matchday</span>
                            </div>
                          ) : (
                            <div key={m.id} className="flex flex-col sm:flex-row sm:items-center gap-4 py-3 border-b border-white/5 last:border-0 hover:bg-white/5 transition-colors pl-2 sm:pl-8">
                               <span className="text-[10px] font-black uppercase text-white/40 w-16 shrink-0">Match {m.matchNumber}</span>
                               <div className="flex-1 flex flex-col sm:flex-row items-start sm:items-center gap-2 sm:gap-4 text-xs font-black uppercase">
                                  <span className="text-yellow-400 font-bold max-w-[200px] truncate" title={m.homeTeamName}>{m.homeTeamName}</span>
                                  <span className="text-white/20">🆚</span>
                                  <span className="text-white font-bold max-w-[200px] truncate" title={m.awayTeamName}>{m.awayTeamName}</span>
                               </div>
                               <div className="mt-2 sm:mt-0 relative group shrink-0">
                                  <input 
                                    type="date" 
                                    value={m.scheduledDate} 
                                    onChange={(e) => updateMatchDate(m.id, e.target.value)}
                                    className="bg-transparent border border-white/10 hover:border-fc-neon-green/50 outline-none text-[10px] uppercase font-black tracking-widest text-white/60 p-2 rounded-sm cursor-pointer transition-all w-36"
                                  />
                               </div>
                            </div>
                          ))}
                       </div>
                    )}
                 </div>
               );
             })}
          </div>
        </div>
      )}

      {/* Balance Modal */}
      {showBalanceModal && stats && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
           <div className="bg-fc-purple-dark border border-white/10 rounded-sm max-w-2xl w-full max-h-[90vh] flex flex-col overflow-hidden shadow-2xl">
              <div className="p-6 border-b border-white/5 flex justify-between items-center bg-black/20">
                 <h3 className="text-lg font-black italic uppercase text-fc-neon-green tracking-tighter flex items-center gap-3">
                   <Users className="w-5 h-5" /> Home/Away Balance
                 </h3>
                 <button onClick={() => setShowBalanceModal(false)} className="text-white/40 hover:text-white p-2">
                   <X className="w-5 h-5" />
                 </button>
              </div>
              <div className="overflow-y-auto p-6 space-y-4">
                 {teams.length % 2 === 0 && (
                   <p className="text-yellow-500/80 text-[10px] uppercase font-bold tracking-wider p-3 bg-yellow-500/10 border-l border-yellow-500/50">
                     ⚠️ Even teams: max 1 home game difference per team — this is mathematically unavoidable
                   </p>
                 )}
                 <table className="w-full text-left text-xs uppercase font-black">
                   <thead>
                     <tr className="border-b border-white/10 text-white/40">
                       <th className="py-3 px-4">Team Name</th>
                       <th className="py-3 px-4 text-center">Home</th>
                       <th className="py-3 px-4 text-center">Away</th>
                       <th className="py-3 px-4 text-center">Total</th>
                     </tr>
                   </thead>
                   <tbody className="divide-y divide-white/5">
                     {teams.map(t => (
                       <tr key={t.id} className="hover:bg-white/5 transition-colors">
                         <td className="py-3 px-4 text-white/80">{t.fcName}</td>
                         <td className="py-3 px-4 text-center text-fc-neon-green">{stats.hCount[t.fcName]}</td>
                         <td className="py-3 px-4 text-center text-red-400">{stats.aCount[t.fcName]}</td>
                         <td className="py-3 px-4 text-center text-white/40">{stats.hCount[t.fcName] + stats.aCount[t.fcName]}</td>
                       </tr>
                     ))}
                   </tbody>
                 </table>
              </div>
           </div>
        </div>
      )}

      {/* Preview Modal */}
      {previewData && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
          <div className="bg-fc-purple-dark border border-white/10 rounded-sm max-w-4xl w-full max-h-[90vh] flex flex-col overflow-hidden shadow-2xl shadow-fc-neon-green/10">
            <div className="p-6 border-b border-white/5 flex justify-between items-center bg-black/20">
               <div>
                  <h3 className="text-xl font-black italic uppercase text-fc-neon-green tracking-tighter flex items-center gap-3">
                    <Settings2 className="w-6 h-6" /> Schedule Preview
                  </h3>
                  <p className="text-white/40 text-[10px] font-black uppercase tracking-widest mt-2 flex items-center gap-2">
                    Teams: {teams.length} | Matches: {previewData.stats.totalMatches} | Days: {previewData.stats.totalDays} <br />
                    {previewData.stats.startDate} → {previewData.stats.endDate}
                  </p>
               </div>
               <button onClick={() => !isSaving && setPreviewData(null)} className="text-white/40 hover:text-white p-2" disabled={isSaving}>
                 <X className="w-6 h-6" />
               </button>
            </div>
            
            <div className="flex-1 overflow-y-auto hide-scrollbar p-6 space-y-8 bg-gradient-to-b from-transparent to-black/20">
              
              <div className="bg-white/5 border border-fc-neon-green/20 rounded-sm p-6 relative overflow-hidden">
                 <div className="absolute top-0 right-0 p-8 w-32 h-32 bg-fc-neon-green/5 rounded-bl-full pointer-events-none" />
                 <h4 className="text-[10px] font-black uppercase tracking-widest text-fc-neon-green mb-4 flex items-center gap-2">
                    <Users className="w-4 h-4" /> Home/Away Balance Table
                 </h4>
                 {teams.length % 2 === 0 && (
                   <p className="text-yellow-500/80 text-[10px] uppercase font-bold tracking-wider mb-4 p-2 bg-yellow-500/10 border-l border-yellow-500/50">
                     ⚠️ Even teams: max 1 home game difference per team — this is mathematically unavoidable
                   </p>
                 )}
                 <div className="overflow-x-auto">
                   <table className="w-full text-left text-xs uppercase font-black">
                     <thead>
                       <tr className="border-b border-white/10 text-white/40">
                         <th className="py-2 px-4">Team Name</th>
                         <th className="py-2 px-4 text-center">Home</th>
                         <th className="py-2 px-4 text-center">Away</th>
                         <th className="py-2 px-4 text-center">Total</th>
                       </tr>
                     </thead>
                     <tbody className="divide-y divide-white/5">
                       {teams.map(t => (
                         <tr key={t.id} className="hover:bg-white/5 transition-colors">
                           <td className="py-2 px-4 text-white/80">{t.fcName}</td>
                           <td className="py-2 px-4 text-center text-fc-neon-green">{previewData.stats.homeCount[t.fcName]}</td>
                           <td className="py-2 px-4 text-center text-red-400">{previewData.stats.awayCount[t.fcName]}</td>
                           <td className="py-2 px-4 text-center text-white/40">{previewData.stats.homeCount[t.fcName] + previewData.stats.awayCount[t.fcName]}</td>
                         </tr>
                       ))}
                     </tbody>
                   </table>
                 </div>
              </div>

              <div className="space-y-4">
                 <h4 className="text-[10px] font-black uppercase tracking-widest text-white/40 mb-2">Day by Day Breakdown</h4>
                 
                 {Array.from({ length: previewData.stats.totalDays }, (_, i) => i + 1).map(day => {
                   const dayMatches = previewData.matches.filter((m: any) => m.matchday === day);
                   if (dayMatches.length === 0) return null;
                   
                   return (
                     <details key={day} className="bg-black/40 border border-white/5 rounded-sm overflow-hidden group">
                        <summary className="p-4 cursor-pointer text-xs font-black uppercase tracking-widest text-white/60 hover:text-white transition-colors flex items-center justify-between outline-none bg-white/5 group-open:bg-fc-neon-green group-open:text-black">
                          <span>📅 Day {day} — {new Date(dayMatches[0].scheduledDate).toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })} • {dayMatches.length} matches</span>
                          <span className="opacity-50">+</span>
                        </summary>
                        <div className="p-4 space-y-2">
                           {dayMatches.map((m: any) => m.isBye ? (
                             <div key={m.id} className="text-[10px] font-black uppercase tracking-widest text-yellow-500/70 py-2 border-b border-white/5 last:border-0 pl-4">
                               🔄 {m.homeTeamName} — BYE (Round {m.round})
                             </div>
                           ) : (
                             <div key={m.id} className="flex flex-col sm:flex-row sm:items-center justify-between py-2 border-b border-white/5 last:border-0 pl-4 hover:bg-white/5">
                               <span className="text-[10px] font-black uppercase text-white/40 w-16">Match {m.matchNumber}</span>
                               <div className="flex-1 flex items-center justify-center gap-4 text-xs font-black uppercase">
                                 <span className="text-yellow-400 flex-1 text-right truncate">{m.homeTeamName}</span>
                                 <span className="text-white/20">🆚</span>
                                 <span className="text-white flex-1 text-left truncate">{m.awayTeamName}</span>
                               </div>
                             </div>
                           ))}
                        </div>
                     </details>
                   )
                 })}
              </div>

            </div>
            
            <div className="p-6 border-t border-white/5 bg-black/40">
               <div className="mb-4">
                 <p className="text-[10px] font-bold uppercase text-red-500 tracking-wider">⚠️ Existing unplayed fixtures in Matches will be deleted and replaced</p>
                 <p className="text-[10px] font-bold uppercase text-green-500 tracking-wider mt-1">✅ Completed matches will not be touched</p>
               </div>
               
               {isSaving ? (
                 <div className="flex items-center justify-center p-4 bg-fc-neon-green/10 text-fc-neon-green rounded-sm text-sm font-black uppercase tracking-widest border border-fc-neon-green/20 animate-pulse">
                   {saveProgress}
                 </div>
               ) : saveComplete ? (
                   <div className="flex items-center justify-center p-4 bg-green-500/10 text-green-400 rounded-sm text-sm font-black uppercase tracking-widest border border-green-500/20">
                     ✅ Done! {previewData.stats.totalMatches} matches scheduled across {previewData.stats.totalDays} days
                   </div>
               ) : (
                 <div className="flex items-center justify-end gap-4 mt-6">
                   <button onClick={() => setPreviewData(null)} className="px-6 py-4 text-white/60 hover:text-white text-[10px] font-black uppercase tracking-widest transition-colors rounded-sm hover:bg-white/5">
                     ❌ Cancel
                   </button>
                   <button onClick={handleSave} className="px-8 py-4 bg-fc-neon-green text-black hover:bg-fc-purple-light rounded-sm font-black uppercase text-xs tracking-widest transition-all shadow-xl shadow-fc-neon-green/20 flex items-center gap-2">
                     <Save className="w-4 h-4" /> Confirm & Generate
                   </button>
                 </div>
               )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
